spring:
  application:
    name: log-scanner
  profiles:
    active: local

  batch:
    job:
      enabled: false

batch:
  redo-log-print:
    enabled: ${REDO_LOG_PRINT_BATCH_ENABLED:true}
    max-rows: ${REDO_LOG_PRINT_BATCH_MAX_ROWS:100}

logminer:
  starter:
    enabled: ${LOGMINER_STARTER_ENABLED:false}
  targets:
    - P_USERS

cdc:
  kafka:
    topic: ${CDC_KAFKA_TOPIC:cdc-log-entries}

management:
  health:
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
