package com.practice.dataloader.failure;

public enum FailureType {

	DESERIALIZATION_FAILED,
	UNSUPPORTED_TABLE,
	UNSUPPORTED_OPERATION,
	MISSING_REQUIRED_FIELD,
	MISSING_KEY,
	TYPE_CONVERSION_FAILED,
	TIMESTAMP_PARSE_FAILED,
	MYSQL_WRITE_FAILED,
	UNKNOWN_LOAD_FAILED

}
