package com.practice.datatransformer.failure;

public enum FailureType {

	DESERIALIZATION_FAILED,
	UNSUPPORTED_TABLE,
	UNSUPPORTED_OPERATION,
	MISSING_REQUIRED_FIELD,
	SOURCE_KEY_LOOKUP_FAILED,
	PAYLOAD_PARSE_FAILED,
	UNKNOWN_TRANSFORM_FAILED

}
