server:
  port: 8081
spring:
  application:
    name: data-transformer
  profiles:
    active: local

cdc:
  kafka:
    input-topic: ${CDC_KAFKA_INPUT_TOPIC:cdc-log-entries}
    output-topic: ${CDC_KAFKA_OUTPUT_TOPIC:cdc-transform-events}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
