spring:
  application:
    name: data-generator
  profiles:
    active: local

  batch:
    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
