DECLARE
	table_count NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO table_count
	FROM user_tables
	WHERE table_name = 'P_USERS';

	IF table_count = 0 THEN
		EXECUTE IMMEDIATE '
			CREATE TABLE p_users (
				id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name VARCHAR2(100) NOT NULL,
				email VARCHAR2(200) NOT NULL UNIQUE,
				status VARCHAR2(20) NOT NULL,
				created_at TIMESTAMP NOT NULL,
				updated_at TIMESTAMP NOT NULL
			)
		';
	END IF;
END;
/
